on:
  workflow_dispatch:
  schedule:
    # run at 00:00:00 everyday (UTC)
    - cron: '0 0 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate (scheduled)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'